apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: streamsets-tls
  namespace: streamsets
spec:
  secretName: streamsets-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - streamsets.archse.eng.br