apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nifi-tls
  namespace: nifi
spec:
  secretName: nifi-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - nifi.archse.eng.br