apiVersion: v1
kind: Secret
metadata:
  name: streamsets-secrets
  namespace: streamsets
type: Opaque
stringData:
  sdc-admin-password: "admin"
  activation-id: "__ACTIVATION_ID__"
  activation-code: "__ACTIVATION_CODE__"
