apiVersion: v1
kind: Secret
metadata:
  name: streamsets-secrets
  namespace: streamsets
type: Opaque
stringData:
  sdc-admin-password: "admin"
  # Descomente e configure se tiver credenciais de ativação
  # streamsets-activation-id: "__ACTIVATION_ID__"
  # streamsets-activation-code: "__ACTIVATION_CODE__"
