apiVersion: v1
kind: Service
metadata:
  name: streamsets-service
  namespace: streamsets
spec:
  selector:
    app: streamsets
  ports:
    - name: http
      protocol: TCP
      port: 18630
      targetPort: 18630
    - name: https
      protocol: TCP
      port: 18631
      targetPort: 18631
  type: ClusterIP
