apiVersion: v1
kind: Service
metadata:
  name: nifi-service
  namespace: nifi
spec:
  selector:
    app: nifi
  ports:
    - name: http
      protocol: TCP
      port: 18630
      targetPort: 18630
    - name: https
      protocol: TCP
      port: 18631
      targetPort: 18631
  type: ClusterIP
